language: Python

python:
  - "2.7"
  - "3.5"

install:
  - pip install coveralls

script:
  - coverage run hello.py
  
after_sucess:
  COVERALLS_REPO_TOKEN=byxaocBq3sRYDvWnG593HHwUkvyVPOZqP coveralls
